Initial config and mostly-complete implementation for cloze highligting
z1lc/zdone pull request #102
Opened 2020-11-09 00:45 UTC by wclausen

Need sql query for readwise highlights and probably some more config stuff to hook everything together properly

2020-11-09 01:44 UTC, z1lc reviewed
Looking really good so far. Some nits, some pointers here.

2020-11-09 01:44 UTC, z1lc commented on app/anki_templates/readwise_highlight_cloze/highlight_cloze_1.html
> +        {{ '{{cloze:Text}}' }}<div id="rsAnkiInternal_clozeTableReplacementAnchor"></div>
We probably don't need `rsAnkiInternal_clozeTableReplacementAnchor` since we won't be converting these notes to cloze tables

2020-11-09 01:44 UTC, z1lc commented on app/card_generation/highlight_clozer.py
> +import spacy
need to add this to the `requirements.txt`

2020-11-09 01:44 UTC, z1lc commented on app/card_generation/highlight_clozer.py
> +    return sentence.replace(keyword, clozed_keyword)
we might want to create some automated tests for this to make sure it does reasonable stuff. I ran into some issues here when doing it for *Grapes of Wrath*: one of the keywords my model identified was `men`, in which case these two were problematic:
>The great companies did not know that the line between hunger and anger is a thin line. And money that might have gone to wages went for gas, for guns, for agents and spies, for blacklists, for drilling. On the highways the people moved like ants and searched for work, for food. And the anger began to fer{{c1::men}}t.

>Wo{{c1::men}} and children knew deep in themselves that no misfortune was too great to bear if their {{c1::men}} were whole.

second example is probably not that huge of a deal but you get the idea.

2020-11-09 01:44 UTC, z1lc commented on app/card_generation/highlight_clozer.py
> +    return longest
`return max(words, key=len)`

2020-11-09 01:44 UTC, z1lc commented on app/card_generation/highlight_clozer.py
> +    if len(result) > 0:
`if result:`

2020-11-09 01:44 UTC, z1lc commented on app/card_generation/readwise.py
> +        # default model ID, but kept existing users on my old model ID for simplicity.
we can remove this because it only corresponds to the Spotify Track model

2020-11-09 01:44 UTC, z1lc commented on app/card_generation/readwise.py
> +    # for now, just return a simple list with one highlight (as a dictionary)
you can either use SQL directly or you can use the SQLAlchemy ORM, which will give it to you in nice object form. It can be hard to get the ORM to do what you want tho, direct SQL tends to be faster for me.

2020-11-09 01:44 UTC, z1lc commented on app/card_generation/readwise.py
> +    for highlight in get_highlights(user):
Wondering what you think about doing the NLP across all highlights from a book, and only after identification of keywords from that 'corpus' do you go into replacing them. In my (very limited) internal testing, that seemed to do a better job of identifying keywords.

2020-11-09 01:44 UTC, z1lc commented on app/card_generation/readwise.py
> +        self._guid = val
you can remove this whole subclass and just use `zdNote` directly -- the reason it was subclassed for the spotify tracks is because of the legacy guid thing, which is not relevant to us here

2020-11-09 03:40 UTC, wclausen commented on app/card_generation/readwise.py
> +    for highlight in get_highlights(user):
i think that's potentially worthwhile, but don't have a strong sense of why that would be better, given the number of highlights isn't generally super large and, at least in my experience, there isn't a ton of overlap in content between highlights. Seems like the kind of thing that could be better in some cases and not better in others, overall being basically like what we have now. Even in a theoretical sense, none of this is really "keyword extraction" (afaik) because it's just identifying named entities/parts of speech (vs attempting to interpret some sort of meaning in the highlight).

Figuring out a solid keyword extraction alg would be very worthwhile, though. Good thing to iterate on. Maybe GPT-3 could do it well.

I would also add that while it would be great to get these cloze cards to be "production quality," it's not even really a major goal for me. I make highlights of things that I just want to be reminded of a couple times, so many of my highlights are never intended to be put into super long term memory. Since my goal is often just to see them a couple times and suspend, time spent investing in making the cloze portions higher quality has a ceiling of value to me that is overall fairly low. I do not currently see a huge difference between "good enough" and "ideal" for my use case.

2020-11-09 04:09 UTC, wclausen commented on app/anki_templates/readwise_highlight_cloze/highlight_cloze_1.html
> +        {{ '{{cloze:Text}}' }}<div id="rsAnkiInternal_clozeTableReplacementAnchor"></div>
👍

2020-11-09 04:09 UTC, wclausen commented on app/card_generation/highlight_clozer.py
> +import spacy
👍

2020-11-09 04:12 UTC, wclausen commented on app/card_generation/highlight_clozer.py
> +    return sentence.replace(keyword, clozed_keyword)
yeah those are problems. I say solve tomorrow/later.

Interesting that it ended up choosing "men" as the cloze there. I guess there weren't any other entities, but seems like companies would have been chosen as a noun before "men." Who knows, this stuff is pretty opaque.

2020-11-09 04:12 UTC, wclausen commented on app/card_generation/highlight_clozer.py
> +    return longest
👍

2020-11-09 04:13 UTC, wclausen commented on app/card_generation/highlight_clozer.py
> +    if len(result) > 0:
👍

2020-11-09 04:14 UTC, wclausen commented on app/card_generation/readwise.py
> +    # for now, just return a simple list with one highlight (as a dictionary)
went with direct sql for speed purposes. seems like sqlalchemy is plenty powerful to do the same thing and it would probably be more readable in the long run. but our queries are pretty simple and so easy to write that no readability is kind of nbd

2020-11-09 04:24 UTC, wclausen commented on app/card_generation/readwise.py
> +    for highlight in get_highlights(user):
Oh as a side note, I mentioned that readwise should do this auto-cloze stuff and he responded by saying that they attempted it at first but also struggled to reliably get the optimal cloze word, and users had a strong negative reaction when it the algorithm made a suboptimal selection. This plays into my suspicion that it's a pretty hard problem to reliably solve in an optimal way, and this simple solution is a strong 80/20 (though it is certainly preferable to not have it cloze out parts of words like Wo{{men}}).

This made sense to me, and highlighted that my use case is probably not the standard one for most folks. As a person looking to make highlights pretty freely, with low commitment towards reviewing any particular card, I have a high tolerance for things being kinda shitty on any given cloze. A single highlight is a dime a dozen. But if I didn't have these habits, it would be a lot more annoying.

Of course, who is opposed to better cloze deletions? Nobody. It would be sick if it could cloze out the ideal word/phrase every time. Even for me (a person optimizing for many highlights at the top of funnel and few at the bottom), better clozes would reduce friction around selecting/improving specific cards for longer-term retention. Reducing friction for getting cards into long term retention is still an unsolved problem, in that sense. My current strategy is just to aggressively filter cards, so that there's only ever like 5-10 for a given book, which I can produce in the old-fashioned, bespoke style of our youth.

2020-11-09 04:24 UTC, wclausen commented on app/card_generation/readwise.py
> +        self._guid = val
👍

2020-11-09 04:25 UTC, wclausen commented on app/card_generation/readwise.py
> +        # default model ID, but kept existing users on my old model ID for simplicity.
copy pasta strikes again

👍

2020-11-09 04:36 UTC, wclausen commented on app/card_generation/highlight_clozer.py
> +    return sentence.replace(keyword, clozed_keyword)
ended up attempting to solve rn, wasn't super complicated, but maybe i made it worse in other ways. i didn't think too hard about it (obv that was my approach the last time too)

2020-11-09 04:47 UTC, z1lc reviewed
few more comments, almost ready to 🚢

2020-11-09 04:47 UTC, z1lc commented on app/anki_templates/readwise_highlight_cloze/highlight_cloze_1.html
> +        {{ '{{#Title}}' }}<span id="rsAnkiContext">{{  '{{Title}}' }}: </span>{{ '{{/Title}}' }}<br>
nit: extra space before `'{{Title}}'` and `</span>`?

2020-11-09 04:47 UTC, z1lc commented on app/anki_templates/readwise_highlight_cloze/highlight_cloze_1.html
> +{{ script_include|safe }}
developing across windows + linux/mac can result in weird line endings, can you run `pre-commit`? Hopefully it's not too annoying to set up -- the README has some notes https://github.com/z1lc/zdone#development

2020-11-09 04:47 UTC, z1lc commented on app/card_generation/readwise.py
> +                clozed_highlight,
we don't have to solve this in this PR but if we use the clozed out text as the first field, we will generate multiple cards if the NLP decides to use a different cloze approach.

2020-11-09 04:47 UTC, z1lc commented on app/card_generation/readwise.py
> +        ON the_highlights.book_id = books.id;
minor but we can simplify this to:

```
select text, title, author
from readwise_books b
         join managed_readwise_books mrb on b.id = mrb.readwise_book_id
         join readwise_highlights rh on mrb.id = rh.managed_readwise_book_id
where mrb.user_id = {user.id}
```

2020-11-09 04:51 UTC, wclausen commented on app/card_generation/readwise.py
> +                clozed_highlight,
maybe we ship our database id's lol

2020-11-09 04:52 UTC, wclausen commented on app/card_generation/readwise.py
> +        ON the_highlights.book_id = books.id;
:

2020-11-09 04:53 UTC, wclausen commented on app/card_generation/readwise.py
> +                clozed_highlight,
i moved it to be just the normal text of the highlight

2020-11-09 04:55 UTC, z1lc commented on app/card_generation/readwise.py
> +                clozed_highlight,
Yeah I think what we probably ultimately want to do is create a log of what the NLP determined the first time for the clozes and just be stuck with that. Using the normal text of the highlight means we avoid the issue of duplicate note creation, but then we might change what the cloze cards are asking us -- or perhaps remove them altogether (eg if before it would have clozed out 2 things from the sentence and it switches to 1, all of a sudden that second card is blank)

2020-11-09 04:56 UTC, z1lc commented on app/card_generation/readwise.py
> +                clozed_highlight,
but I think for MVP those issues are mostly ~fine. We'll see how much of a problem it is soon enough

2020-11-09 04:57 UTC, wclausen commented on app/anki_templates/readwise_highlight_cloze/highlight_cloze_1.html
> +{{ script_include|safe }}
👍

2020-11-09 06:18 UTC, z1lc commented on app/card_generation/readwise.py
> +        ON the_highlights.book_id = books.id;
I'm not sure how many total highlights we'll have but I wonder if this will eventually get too large to hold in memory at once. The Heroku dyno only has 512MB of RAM. We're currently hovering at about 25% memory usage.

2020-11-11 15:12 UTC, wclausen commented on app/card_generation/readwise.py
> +        ON the_highlights.book_id = books.id;
yeah that's fair. this problem could be avoided by requesting only since the last update. can make that as a follow-on issue?

2020-11-11 15:13 UTC, wclausen commented on app/card_generation/readwise.py
> +                clozed_highlight,
yeah i agree. maybe we have another table that gets populated with (readwise_highlight_id, clozed_word) and just check if a given highlight record has a corresponding entry in the other table

2020-11-13 03:14 UTC, z1lc commented on app/card_generation/readwise.py
> +        ON the_highlights.book_id = books.id;
yeah I say we don't worry about it until we start seeing crashes

2020-11-13 03:20 UTC, z1lc requested changes
Final nits before merge -- would love to try it in prod today!

2020-11-13 03:20 UTC, z1lc commented on app/anki_templates/readwise_highlight_cloze/highlight_cloze_1.html
> +        </ul>
I'm not sure `<ul>` is always a block-level element -- you may need a `<br>` above this

2020-11-13 03:20 UTC, z1lc commented on app/card_generation/highlight_clozer.py
> +    if len(ents) == 0:
`if not ents:`

2020-11-13 03:20 UTC, z1lc commented on app/card_generation/highlight_clozer.py
> +        if ent_count > max_count and (ent.label_ not in ["ORDINAL", "CARDINAL"] and ent.start != 0):
do we need the parens here?

2020-11-13 03:20 UTC, z1lc commented on app/card_generation/readwise.py
> +        model_type=genanki.Model.CLOZE
NICE

2020-11-14 03:50 UTC, wclausen commented on app/card_generation/readwise.py
> +        model_type=genanki.Model.CLOZE
yeah it totally didn't work without this

2020-11-14 03:50 UTC, wclausen commented on app/card_generation/highlight_clozer.py
> +        if ent_count > max_count and (ent.label_ not in ["ORDINAL", "CARDINAL"] and ent.start != 0):
nope, i also extracted it into a helper for future clarity

2020-11-14 03:50 UTC, wclausen commented on app/card_generation/highlight_clozer.py
> +    if len(ents) == 0:
👍

2020-11-14 03:50 UTC, wclausen commented on app/anki_templates/readwise_highlight_cloze/highlight_cloze_1.html
> +        </ul>
👍

2020-11-14 03:51 UTC, wclausen commented on app/anki_templates/readwise_highlight_cloze/highlight_cloze_1.html
> +        </ul>
you know *much* more about html than ja boi, grateful for it 🙏

2020-11-14 04:02 UTC, z1lc approved these changes
🚢

2020-11-14 04:02 UTC, merged